version: '3.7'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
        - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      - mysql

volumes:
  db_data:
  wordpress_data:
